apiVersion: v1
kind: Service
metadata:
   name: platform-sync-clusterip-service
spec:
   type: ClusterIP
   selector:
      app: platform-sync
   sessionAffinity: ClientIP
   sessionAffinityConfig:
      clientIP:
         timeoutSeconds: 10
   ports:
      - port: 4000
        targetPort: 4000
